### ISSUE TITLE
cannot unmarshal array into Go struct field with add auth.json

### ISSUE THREAD

**Issue by gavinzhou** [motiv-labs/janus#174]
[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
run janus with docker-compose
```
more docker-compose.yml
version: '3'
services:

  janus:
    image: quay.io/hellofresh/janus
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - service1
      - janus-database
      - janus-storage
    volumes:
      - ./janus.toml:/etc/janus/janus.toml

  janus-database:
      image: mongo
      ports:
        - "27017:27017"

  janus-storage:
      image: redis:3.2
      ports:
        - "6379:6379"

  # This container is just a helper to seed the database
  mongo-seed:
    build:
      context: .
      dockerfile: seed.Dockerfile
    depends_on:
      - janus-database

  service1:
    image: rodolpheche/wiremock
    ports:
      - '9089:8080'
    volumes:
      - ../front-proxy/stubs:/home/wiremock/mappings
```
2. [Second Step]
add auth.json 
```
more auth/auth.json
{
    "name" : "local",
    "oauth_endpoints" : {
        "token" : {
            "preserve_host" : false,
            "listen_path" : "/auth/token",
            "upstream_url" : "http://auth-service:8080/token",
            "strip_path" : true,
            "append_path" : false,
            "enable_load_balancing" : false,
            "methods" : [
                "GET",
                "POST"
            ]
        }
    },
    "token_strategy" : {
        "name" : "jwt",
        "settings" : [
            {"alg": "HS256", "key" : "secret"}
        ]
    }
}
```

**Expected behavior:**

[Describe expected behavior here]
```
http POST localhost:8081/oauth/servers "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDA2ODM0NTQsImlhdCI6MTUwMDY3OTg1NCwiaWQiOiJhZG1pbiJ9.8EgMguMUept5WRUbz29QgfQOCZ4PtWcwA65ja8Igi9E" < auth.json
HTTP/1.1 500 Internal Server Error
Content-Encoding: gzip
Content-Length: 111
Content-Type: application/json
Date: Fri, 21 Jul 2017 23:31:21 GMT
Vary: Origin

"json: cannot unmarshal array into Go struct field TokenStrategy.settings of type oauth.TokenStrategySettings"
```
[Describe observed behavior here]

**Janus version:** [Enter Atom version here]
```
[root@ip-172-31-10-54 auth]# http localhost:8081
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 58
Content-Type: application/json
Date: Fri, 21 Jul 2017 23:31:56 GMT
Vary: Origin

"Welcome to Janus v3.2.0-3c4d321"
```
**OS and version:** [Enter OS name and version here]
